version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - "./.env.prod"
